### PR TITLE
Fix bug when URL in config file

### PR DESCRIPTION
**Pull request by hans00**

### CODE REVIEW

**Comment by mfuentesg** [comment]
@hans00 can you give more context what this is trying to fix? or, can you create an issue for it?

**Comment by mfuentesg** [comment]
Validating the expression some cases are not covered.

i have modified a bit your expression -> https://regex101.com/r/U46FhM/1/.

**Comment by hans00** [comment]
Issue #177

**Comment by hans00** [comment]
I found decode function in v3 API, but v2 doesn't have.
Does we stop support v2?

**Comment by mfuentesg** [comment]
I tried, but some issues with special chars still happen after using `sublime.decode_value` or `sublime.encode_value`

**Comment by mfuentesg** [comment]
@hans00  i will use your first approach to fix this issue, in order to solve it now. I will spend more time finding another way to cover more escenarios. 

https://github.com/mfuentesg/SyncSettings/pull/178

**Pull request closed without merging**
