### PR TITLE
incomplete tutorial corrected.

### PR DESCRIPTION
**Pull request by hazarek**
incomplete tutorial corrected. If there is no gist, it must be created.

### CODE REVIEW

**Comment by mfuentesg** [comment]
@hazarek gist id is not necessary required at first time, because it will be created automatically by the plugin if it does not exist or if is not defined in the configuration file.

**Comment by hazarek** [comment]
> @hazarek gist id is not necessary required at first time, because it will be created automatically by the plugin if it does not exist or if is not defined in the configuration file.

@mfuentesg You closed the pull request without listening to my answer. this is irresponsible and disrespectful behavior.

Gist gives this error if it doesn't have id property.
Ekran Resmi 2020-12-14 06 12 35

**Comment by hazarek** [comment]
You mislead people and waste their time. idiots.

**Comment by mfuentesg** [comment]
Hello @hazarek , apparently somebody had a really bad day. 
Anyways, if you are treating people as idiot, don't request respect, it is "a bit" contractory.

Enjoy SyncSettings. Bye!

**Comment by hazarek** [comment]
hasiktir lan yavşak

**Pull request closed without merging**
