### PR TITLE
Resolves #188

### LINKED ISSUE #188: Open settings side-by-side with one command instead of separately in two commands
See, how internal Settings open. There is one menu item:

settings menu

And it opens default settings and user-specified:

image

This is done with `edit_settings` command (in `.sublime-menu` file):

```json
{
	"command": "edit_settings",
	"args": { "base_file": "${packages}/.../....sublime-settings" },
	"caption": "Settings"
}
```

This can be implemented for SyncSettings too!

### PR DESCRIPTION
**Pull request by mariohuq**
After this change menu looks like

image

And settings open like this

image

### CODE REVIEW

**Comment by mfuentesg** [comment]
@mariohuq could u tell me what is the behavior for sublime text v2? if everything works fine, we can merge it.

**Comment by mariohuq** [comment]
> @mariohuq could u tell me what is the behavior for sublime text v2? if everything works fine, we can merge it.

`edit_settings` doesn't work for Sublime Text 2, unfortunately.

**Comment by mfuentesg** [comment]
@mariohuq sync settings won't work on sublime text 2 anymore

**Comment by mfuentesg** [comment]
@all-contributors adds @mariohuq as a contributor for code.

**Comment by mfuentesg** [comment]
@all-contributos please add @mariohuq for code

**Comment by mfuentesg** [comment]
@all-contributors please add @mariohuq as a contributor for code.

**Pull request merged**
